services:
  app:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    networks:
      app_net:
      proxy_net:
        aliases:
          - simpleExample-app
    restart: unless-stopped

networks:
  app_net:
    driver: bridge

  proxy_net:
    external: true
    name: proxy_net
